name: tourism
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0 # Ensure this is the latest version

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  cloud_firestore: ^5.4.4

  http: ^1.2.2
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/image.png
    - assets/images/home/dashboard_background.png
    - assets/images/home/web.png
    - assets/images/home/rect.png
    - assets/images/home/arrow.png
    - assets/images/home/plane.png
    - assets/images/home/bag.png
    - assets/images/home/bar.png
    - assets/images/home/home.png
    - assets/images/home/profile.png
    - assets/images/backAppBar.png

  fonts:
    - family: PlaywriteUS
      fonts:
        - asset: assets/fonts/PlaywriteUS-TRAD.ttf
